---
title: "Assignment 4"
author: "Ian Brunjes, Tom Wheeler, Aya Rosenfeld"
date: "5/20/2021"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(broom)
library(patchwork)
```

## 1. 


```{r}

# Read in data
data_dmg <- read.csv(here("data", "damages.csv")) %>% clean_names()
data_wrm <- read.csv(here("data", "warming.csv")) %>% clean_names()

# Prelim plots
#data_dmg %>% ggplot(aes(x = warming, y = damages)) + geom_point() + stat_smooth(se = TRUE)
#data_wrm %>% ggplot(aes(x = x, y = warming_baseline)) + geom_point() + stat_smooth(se = TRUE)
#data_wrm %>% ggplot(aes(x = x, y = warming_pulse)) + geom_point() + stat_smooth(se = TRUE)

# Variables
pulse <- 35*10^9 # tons of CO2

####
# 1.
####

# Fit quadratic model
# Create a new column in data frame to represent squared values of our dependent var (warming)
data_dmg <- data_dmg %>% mutate(warming_sq = warming^2)
# Using warming values and warming squared values, do quadratic regression
quad_dmg <- lm(damages ~ warming_sq + warming + 0, data = data_dmg)
#summary(quad_dmg)

# USe coefficients from regression to create funtion like: ax^2 + bx + 0
damages_model <- function(x) {
  out <- quad_dmg$coefficients[["warming_sq"]]*(x^2) + quad_dmg$coefficients[["warming"]]*x + 0
  return(out)
}

# Plot model over data points
ggplot(data = data_dmg, mapping = aes(x = warming, y = damages)) +
  xlim(0,10) +
  geom_point(col = "red") +
  stat_function(fun = damages_model, size = 2)+
  labs(x = "Warming (C)", y = "Damages ($)")
```

## 2.

#### A)

```{r}

# Use damages model function to make predictions based on anticipated warming
data_wrm <- data_wrm %>%
  mutate(predicted_baseline = damages_model(warming_baseline)) %>% # Predict damages for baseline warming data
  mutate(predicted_pulse = damages_model(warming_pulse)) %>% # Predict damages for baseline warming data
  mutate(predicted_diff = predicted_pulse - predicted_baseline) %>% # Difference in damages between pulse and baseline
  mutate(dmg_per_ton = predicted_diff/pulse) # Differences in damage

# Plot 1: Damages over time without the pulse
data_wrm %>% 
  ggplot(aes(x = x, y = predicted_baseline)) +
  geom_point() +
  labs(x = "Years (from 2020)", y = "Predicted damages ($)")
```

#### B)

```{r}
# Plot 2: Damages over time with the pulse
data_wrm %>% 
  ggplot(aes(x = x, y = predicted_pulse)) +
  geom_point() +
  labs(x = "Years (from 2020)", y = "Predicted damages ($)")
```


#### C)

```{r}
# Plot 3: Difference in damages over time between pulse/no-pulse
data_wrm %>% 
  ggplot(aes(x = x, y = predicted_diff)) +
  geom_point() +
  labs(x = "Years (from 2020)", y = "Predicted differences ($)")
```

#### D)

```{r}
# Plot 4: Difference in damages over time per ton of CO2
data_wrm %>% 
  ggplot(aes(x = x, y = dmg_per_ton)) +
  geom_point() +
  labs(x = "Years (from 2020)", y = "Difference in damage per ton of CO2 ($)")
```

## 3.

```{r}
####
# 3.
####

# We need to somehow use the dmg_per_ton values from #2 Plot 4 to infer SCC
# SCC = PV with carbon pulse - PV without carbon pulse

# Funtion of calculate present value using sum of series
# Xt/(1+r)^t
PV_calc <- function(values, discount_rate = 0.02) {
  sum <- 0;
  r <- discount_rate
  for (i in c(1:length(values))) {
    current <- values[i]/(1 + r)^i
    sum <- sum + current
  }
  
  return(sum)
}

# discount rates representing 0.5% intervals between 1%-10%
dr <- seq(0, .1, 0.005)

# Calculate SCC by finding present value of per ton damage at each discount rate in range
scc_values <- PV_calc(data_wrm$dmg_per_ton, dr)

# Create a data
scc_points <- data.frame(discount_rate <- dr, scc <- scc_values)
colnames(scc_points) <- c("discount_rate","scc")

# Plot, translate discount rate to percents
ggplot(data = scc_points, mapping = aes(x = discount_rate * 100, y = scc)) +
  geom_point(size = 2) +
  labs(x = "Discount Rate (%)", y = "SCC ($)") +
  scale_x_continuous(breaks = seq(0, 10, 1))
```


## 4.

```{r}
####
# 4.
####

# Ramsey Rule variables
p <- 0.001
n <- 2
g <- 0.01

ramsey_rule <- function(p, n, g) {
  p + n*g
}

rr_discount <- ramsey_rule(p,n,g)
rr_scc <- PV_calc(data_wrm$dmg_per_ton, rr_discount)

# This will depend on #3
# scc_rr <- scc_model(rr_discount_pct)
ggplot(data = scc_points, mapping = aes(x = discount_rate * 100, y = scc)) +
  geom_point(size = 2) +
  labs(x = "Discount Rate (%)", y = "SCC ($)") +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  geom_point(aes(x = rr_discount * 100, y = rr_scc), col = "red", size = 3)
```

Ramsey rule discount rate: `r rr_discount`

SCC: `r rr_scc`

## 5.

```{r}
####
# 5.
####

# Create hypothetical warming/damage values under each scenario
data_wrm <- data_wrm %>%
  mutate(warming_baseline_150 = warming_baseline * 1.5) %>% # Scenario A warming
  mutate(predicted_baseline_150 = damages_model(warming_baseline_150)) %>% # Scenario A damages
  mutate(warming_baseline_2050 = 
           case_when( year > 2050 ~ 1.29,
                     TRUE ~ warming_baseline
          )) %>% # Scenario B warming
  mutate(predicted_baseline_2050 = damages_model(warming_baseline_2050)) #Scenario B damages
  

# Calculate Present Value (PV) for the damages of each possibility in Scenario A
A_baseline <- PV_calc(data_wrm$predicted_baseline, 0.02)
A_baseline_150 <- PV_calc(data_wrm$warming_baseline_150, 0.02)

# Use their probabilities (each 50% likely to occur) to get a total value
A_expected_value <- (A_baseline * 0.5) + (A_baseline_150 * 0.5)


# Calculate PV for damages predicted under Scenario B
B_expected_value <- PV_calc(data_wrm$predicted_baseline_2050, 0.02)

# How to get "max cost"
# Is it simply the difference between the two outcomes?
max_cost <- A_expected_value - B_expected_value # ?????
```

#### Policy A:

Expected present value of damages up to 2100: `r A_expected_value`

#### Policy B:

Expected present value of damages up to 2100: `r B_expected_value`

If Policy A costs 0 and Policy B costs X, the value for X can be as high as `r max_cost` for it to still make economic sense to pursue B over A.

If society were risk averse, we would expect ???

